
# This file is designed to be used with vscode REST client extension
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

# Configure your Cloud Run URL in settings.json (could be just for a workspace)
# {
#   "rest-client.environmentVariables": {
#     "$shared": {
#       "api-demo-url": "https://api-demo-*****-uc.a.run.app"
#     }
#   }
# }

get {{ api-demo-url }}

###

get {{ api-demo-url }}/api/v1/openapi.json

### https://{{ api-demo-url }}/docs

### 

get {{ api-demo-url }}/api/v1/users
Authorization: Bearer {{token}}

###

get {{ api-demo-url }}/api/v1/cars?limit=3
Authorization: Bearer {{token}}

### 

get {{ api-demo-url }}/api/v1/cars?q=make=Tesla
Authorization: Bearer {{token}}

### 

get {{ api-demo-url }}/api/v1/cars?q=make=Tesla,year=2019
Authorization: Bearer {{token}}


### 

get {{ api-demo-url }}/api/v1/cars?q=make=Toyota,year=gt~2018
Authorization: Bearer {{token}}

### 

get {{ api-demo-url }}/api/v1/cars?q=year=gt~2018,body_styles=ac~Wagon
Authorization: Bearer {{token}}

### multiple range on year

get {{ api-demo-url }}/api/v1/cars?q=year=gt~2016,year=lt~2019
Authorization: Bearer {{token}}


###
# @name createRequest
post {{ api-demo-url }}/api/v1/cars
Authorization: Bearer {{token}}
content-type: application/json

 {
    "make": "Gizmo-mobiles",
    "model": "nifty",
    "year": 2019,
    "body_styles": [
      "Sedan",
      "Wagon"
    ]
  }

###
get {{ api-demo-url }}/api/v1/cars?q=make=Gizmo-mobiles
Authorization: Bearer {{token}}

###
@carId = {{createRequest.response.body.$.id}}
get {{ api-demo-url }}/api/v1/cars/{{ carId }}
Authorization: Bearer {{token}}

###
delete {{ api-demo-url }}/api/v1/cars/{{ carId }}
Authorization: Bearer {{token}}

###
# note this should be an error as path and body id do not match
put {{ api-demo-url }}/api/v1/cars/Acura_TLX_2017
Authorization: Bearer {{token}}

  {
    "id": "Acura_TLX_2017xyz",
    "make": "Acura",
    "model": "TLXXX",
    "year": 2017,
    "body_styles": [
      "Sedan"
    ]
  }

###
# note this should *not* be an error
put {{ api-demo-url }}/api/v1/cars/Acura_TLX_2017
Authorization: Bearer {{token}}

  {
    "id": "Acura_TLX_2017",
    "make": "Acura",
    "model": "TLzzz",
    "year": 2017,
    "body_styles": [
      "Sedan"
    ]
  }

###
get {{ api-demo-url }}/api/v1/cars?q=make=Acura,year=2017
Authorization: Bearer {{token}}


###
get {{ api-demo-url }}/api/v1/cars/Acura_CL_1997 
Authorization: Bearer {{token}}

###
put https://api-demo-gateway-avzcrpvnta-uc.a.run.app/api/v1/cars/Acura_CL_1997
Authorization: Bearer {{token}}

{
  "id": "Acura_CL_1997",
  "make": "Acura",
  "model": "CLzzzz",
  "year": 1997,
  "body_styles": [
    "Coupe"
  ]
}