
# This file is designed to be used with vscode REST client extension
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

# Configure your Cloud Run URL in settings.json (could be just for a workspace)
# {
#   "rest-client.environmentVariables": {
#     "$shared": {
#       "api-demo-url": "https://api-demo-*****-uc.a.run.app"
#     }
#   }
# }

get {{ api-demo-url }}

###

get {{ api-demo-url }}/api/v1/openapi.json

### https://{{ api-demo-url }}/docs

### 

get {{ api-demo-url }}/api/v1/users

###

get {{ api-demo-url }}/api/v1/cars?limit=3

### 

get {{ api-demo-url }}/api/v1/cars?q=make=Tesla

### 

get {{ api-demo-url }}/api/v1/cars?q=make=Tesla,year=2019


### 

get {{ api-demo-url }}/api/v1/cars?q=make=Toyota,year=gt~2018

### 

get {{ api-demo-url }}/api/v1/cars?q=year=gt~2018,body_styles=ac~Wagon

### multiple range on year

get {{ api-demo-url }}/api/v1/cars?q=year=gt~2016,year=lt~2019


###
# @name createRequest
post {{ api-demo-url }}/api/v1/cars
content-type: application/json

 {
    "make": "Gizmo-mobiles",
    "model": "nifty",
    "year": 2019,
    "body_styles": [
      "Sedan",
      "Wagon"
    ]
  }

###
get {{ api-demo-url }}/api/v1/cars?q=make=Gizmo-mobiles

###
@carId = {{createRequest.response.body.$.id}}
get {{ api-demo-url }}/api/v1/cars/{{ carId }}

###
delete {{ api-demo-url }}/api/v1/cars/{{ carId }}